// Generated by CoffeeScript 1.7.1
(function() {
  var exec, ext, files, listOfFiles, projectName, src;

  exec = require("child_process").exec;

  projectName = "gofer.js";

  src = "src/";

  ext = ".coffee";

  files = ["pubsub", "jquery-plugins", "core", "gofer-classes"];

  listOfFiles = function() {
    var arr, file;
    arr = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        _results.push("" + src + file + ext);
      }
      return _results;
    })();
    return arr.join(" ");
  };

  task("watch", "Build project from src/*.coffee to lib/*.js", function() {
    return exec((" coffee -w -j " + projectName + " -c -o lib/ ") + listOfFiles(), function(err, stdout, stderr) {
      if (err) {
        throw err;
      }
      return console.log(stdout + stderr);
    });
  });

  task("build", "Build project from src/*.coffee to lib/*.js", function() {
    return exec((" coffee -j " + projectName + " -c -o lib/ ") + listOfFiles(), function(err, stdout, stderr) {
      if (err) {
        throw err;
      }
      return console.log(stdout + stderr);
    });
  });

}).call(this);
