// Generated by CoffeeScript 1.6.3
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
  __slice = [].slice;

(function($) {
  var attach, beginPrefetch, config, detatch, fnGofer, goferCache, goferGo, goferLoad, goferOff, handleClick, handlePop, insertScriptTags, makeConfig, prefetch, preloadImages, putAndPush, queueRequest, shiftQueue, storeThisPage, utils;
  config = {};
  makeConfig = function(context, where, options, callback) {
    var defaults, goferConfiguration, i, o, settings, _i, _len;
    defaults = {
      loadingClass: "gofer-loading",
      prefetch: true,
      limit: 0,
      animate: 250,
      stripOut: false,
      preloadImg: true,
      runScripts: true,
      customData: {},
      customHeader: []
    };
    config = {
      links: context,
      $links: $(context),
      selector: $(context).selector,
      $html: $("html"),
      $body: $("body"),
      $window: $(window),
      selectors: [],
      targets: [],
      imgCache: [],
      $targets: {},
      limit: 0
    };
    if (typeof where === "boolean" && where === false) {
      goferOff();
    }
    if (typeof where === "string") {
      config.targets[0] = config.$targets[where] = $(where);
      config.selectors[0] = where;
    } else if ($.isPlainObject(where)) {
      config.targets[0] = config.$targets[where.target] = $(where.target);
      config.selectors[0] = where.selector === "same" ? where.target : where.selector;
    } else if ($.isArray(where)) {
      for (i = _i = 0, _len = where.length; _i < _len; i = ++_i) {
        o = where[i];
        config.targets[i] = config.$targets[o.target] = $(o.target);
        config.selectors[i] = o.selector === "same" ? o.target : o.selector;
      }
    }
    if (options) {
      if ($.isFunction(options)) {
        config.callback = options;
        settings = defaults;
        options = {};
      } else if ($.isPlainObject(options) && callback) {
        config.callback = callback;
      }
    } else {
      options = {};
    }
    return goferConfiguration = $.extend(true, {}, defaults, options, config);
  };
  handleClick = function(event, link) {
    var path;
    path = link.pathname;
    if (event.which > 1 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) {
      return;
    }
    if (window.sessionStorage[path] != null) {
      putAndPush(path, true);
      if (config.callback) {
        config.callback(config.targets, "local", "success");
      }
    } else {
      goferLoad(path);
    }
  };
  goferOff = function() {
    config.$body.off("click.gofer");
    return config.$window.off("popstate.gofer");
  };
  fnGofer = function(where, options, callback) {
    if (typeof where === "boolean" && where === false) {
      goferOff();
      return this;
    }
    config = makeConfig(this, where, options, callback);
    config.$body.on("click.gofer", "" + config.selector, function(event) {
      var active;
      if (event.which > 1 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) {
        return this;
      }
      if (this.tagName.toUpperCase() !== 'A') {
        return this;
      }
      if (location.protocol !== this.protocol) {
        return this;
      }
      if (location.hostname !== this.hostname) {
        return this;
      }
      if (this.hash && this.href.replace(this.hash, '') === location.href.replace(location.hash, '')) {
        return this;
      }
      if (this.href === location.href + '#') {
        return this;
      }
      if (config.limit) {
        active = $(config.selector).slice(0, limit);
        if (!$(this).is(active)) {
          return this;
        }
      }
      event.preventDefault();
      return handleClick(event, this);
    });
    $(window).on("popstate.gofer", function(event) {
      return handlePop(event);
    });
    storeThisPage();
    if (config.prefetch) {
      return beginPrefetch();
    }
  };
  handlePop = function(event) {
    var state;
    state = event.originalEvent.state;
    if (state && window.sessionStorage[state.path]) {
      putAndPush(state.path, false);
    }
  };
  storeThisPage = function() {
    var i, selector, tempArr, _i, _len, _ref;
    tempArr = [];
    _ref = config.selectors;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      selector = _ref[i];
      tempArr[i] = {};
      tempArr[i].html = $(selector).html() || "oops";
      tempArr[i].target = config.targets[i].selector;
    }
    return window.sessionStorage.setItem(window.location.pathname, JSON.stringify(tempArr));
  };
  beginPrefetch = function() {
    var $links;
    $links = $(config.selector);
    if (config.limit) {
      $links = $links.slice(0, limit);
    }
    return $links.each(function(i) {
      var path;
      path = this.pathname;
      if (window.sessionStorage.getItem(path) != null) {

      } else {
        return queueRequest(path, false);
      }
    });
  };
  insertScriptTags = function() {
    return $(".script-placeholder").each(function() {
      var key, replacer, val, _ref;
      replacer = $("<script>");
      _ref = $(this).data();
      for (key in _ref) {
        val = _ref[key];
        replacer.attr(key, val);
      }
      return $(this).replaceWith(replacer);
    });
  };
  putAndPush = function(path, pushIt) {
    var actualPush, actualPut, duration, first, partials;
    partials = JSON.parse(window.sessionStorage.getItem(path));
    first = true;
    actualPut = function() {
      var i, partial, _i, _len;
      for (i = _i = 0, _len = partials.length; _i < _len; i = ++_i) {
        partial = partials[i];
        config.$targets[partial.target].html(partial.html);
      }
      if (config.runScripts) {
        insertScriptTags();
      }
      if (pushIt) {
        actualPush();
      }
      if (config.prefetch) {
        beginPrefetch();
      }
    };
    actualPush = function() {
      window.history.pushState({
        path: path
      }, null, path);
    };
    if (config.animate) {
      duration = typeof config.animate === "boolean" ? 250 : config.animate;
      $(config.selectors.join(", ")).animate({
        opacity: 0
      }, duration, function() {
        if (first === true) {
          first = false;
          actualPut();
        }
        return $(this).animate({
          opacity: 1
        }, duration);
      });
    } else {
      actualPut();
    }
    config.$window.trigger("goferUpdate", config.selectors);
  };
  goferLoad = function(path, immediate) {
    if (immediate) {
      config.$html.addClass(config.loadingClass);
    }
    return $.ajax({
      url: path,
      type: "GET",
      dataType: "html",
      context: config.$html,
      data: config.customData,
      beforeSend: function(xhr) {
        if (!$.isEmptyObject(config.customHeader)) {
          return xhr.setRequestHeader(config.customHeader[0], config.customHeader[1]);
        }
      },
      error: function(xhr, status, error) {
        return console.error(error);
      },
      success: function(data, status, xhr) {
        var $data, i, selector, tempArr, _i, _len, _ref;
        tempArr = [];
        $data = $(data);
        if (config.runScripts) {
          $data.find("script").each(function(i, el) {
            var attribute, replacer, _i, _len, _ref;
            replacer = $("<div class='script-placeholder'>");
            _ref = this.attributes;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              attribute = _ref[_i];
              replacer.data(attribute.name, attribute.value);
            }
            return $(this).replaceWith(replacer);
          });
        }
        _ref = config.selectors;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          selector = _ref[i];
          tempArr[i] = {};
          tempArr[i].html = $("<div>").append($data).find(selector).html() || "";
          tempArr[i].target = config.targets[i].selector;
          if (!immediate && config.preloadImg) {
            preloadImages(tempArr[i].html);
          }
        }
        window.sessionStorage.setItem(path, JSON.stringify(tempArr));
        if (immediate) {
          return putAndPush(path, true);
        } else {
          return shiftQueue(path);
        }
      },
      complete: function(text, status, xhr) {
        var element, targets;
        console.log("request to " + path + " complete: " + status);
        if (immediate) {
          $(this).removeClass(config.loadingClass);
          if (config.callback) {
            targets = (function() {
              var _i, _len, _ref, _results;
              _ref = config.targets;
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                element = _ref[_i];
                _results.push(element.selector);
              }
              return _results;
            })();
            return config.callback(targets, "ajax", status);
          }
        }
      }
    });
  };
  preloadImages = function(htmlString) {
    return $(htmlString).find("img").each(function() {
      var img, src;
      src = $(this).src;
      if (__indexOf.call(config.imgCache, src) < 0) {
        img = new Image();
        img.src = src;
        return config.imgCache.push(src);
      }
    });
  };
  prefetch = {
    max: 5,
    pending: [],
    queue: []
  };
  queueRequest = function(url) {
    if (__indexOf.call(prefetch.queue, url) >= 0 || __indexOf.call(prefetch.pending, url) >= 0) {

    } else {
      if (prefetch.pending.length < prefetch.max) {
        prefetch.pending.push(url);
        return goferLoad(url, false);
      } else {
        return prefetch.queue.push(url);
      }
    }
  };
  shiftQueue = function(prev) {
    var url;
    utils.removeVals(prefetch.pending, prev);
    url = prefetch.queue.shift();
    if (url) {
      return queueRequest(url);
    }
  };
  goferGo = function(path) {
    return goferLoad(path, true);
  };
  goferCache = function(path) {
    return queueRequest(path);
  };
  attach = function() {
    $.fn.gofer = fnGofer;
    $.gofer = {};
    $.gofer.go = goferGo;
    $.gofer.cache = goferCache;
    $.gofer.click = handleClick;
    $.gofer.attach = $.noop;
    return $.gofer.detatch = detatch;
  };
  detatch = function() {
    $.fn.gofer = $.noop;
    $.gofer = {};
    $.gofer.go = $.noop;
    $.gofer.cache = $.noop;
    $.gofer.click = $.noop;
    $.gofer.attach = attach;
    return $.gofer.detatch = $.noop;
  };
  $.support.pjax = window.history && window.history.pushState && window.sessionStorage && !navigator.userAgent.match(/((iPod|iPhone|iPad).+\bOS\s+[1-4]|WebApps\/.+CFNetwork)/);
  if ($.support.pjax) {
    attach();
  } else {
    detatch();
  }
  return utils = {
    removeVals: function() {
      var arr, spot, val, vals, _i, _len;
      arr = arguments[0], vals = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      for (_i = 0, _len = vals.length; _i < _len; _i++) {
        val = vals[_i];
        if ((spot = arr.indexOf(val)) !== -1) {
          arr.splice(spot, 1);
        }
      }
      return arr;
    }
  };
})(jQuery);
