// Generated by CoffeeScript 1.6.3
(function($) {
  $.fn.splink = function(targetSelector, callback) {
    var opts, s;
    if (!(window.sessionStorage && window.history.pushState)) {
      return;
    }
    opts = {
      dataAttr: "data-splink-selector",
      htmlClass: "splink-loading",
      animate: false
    };
    s = {
      session: window.sessionStorage,
      elements: this,
      $elements: $(this),
      $selector: $(this).selector,
      $target: $(targetSelector),
      $html: $("html"),
      $body: $("body")
    };
    window.addEventListener("popstate", function(event) {
      s.$target.html(s.session[window.location.pathname]);
    });
    s.$body.on("click", "" + s.$selector, function(event) {
      var e;
      event.preventDefault();
      e = {
        link: this,
        href: this.href,
        path: this.pathname,
        $link: $(this),
        subselector: $(this).attr("data-splink-selector")
      };
      if (s.session[e.path]) {
        s.$target.html(s.session[e.path]);
        window.history.pushState(null, null, e.path);
        console.log("html pulled from sessionStorage");
        return true;
      } else {
        if (!s.session[window.location.pathname]) {
          s.session[window.location.pathname] = s.$target.html();
        }
        s.$target.load("" + e.href + " " + e.subselector, function(response, status, xhr) {
          if (status === "error") {
            console.log("" + xhr.status + " " + xhr.statusText);
          } else {
            window.history.pushState(null, null, e.href);
            s.session[window.location.pathname] = s.$target.html();
          }
          callback(response, status, xhr);
        });
      }
    });
    return this;
  };
})(jQuery);
