// Generated by CoffeeScript 1.7.1
(function() {
  var Gist,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Gofer.Fragment.prototype.getGists = function() {
    var fragment, gistIds, id, _i, _len;
    fragment = this;
    fragment.gists = [];
    gistIds = [];
    fragment.$el.find("script[src^='https://gist.github.com']").each(function() {
      var id, urlPieces;
      urlPieces = this.src.split("/");
      id = urlPieces[urlPieces.length - 1].split(".")[0];
      $(this).replaceWith("<div data-gist-id=" + id + "></div>");
      return gistIds.push(id);
    });
    for (_i = 0, _len = gistIds.length; _i < _len; _i++) {
      id = gistIds[_i];
      fragment.gists.push(new Gofer.Gist({
        id: id,
        parent: fragment
      }));
    }
    return $.subscribe("gofer.pageRenderAll", function(event, page) {
      var gist, _j, _len1, _ref, _results;
      if (page.url === fragment.parent.url) {
        _ref = fragment.gists;
        _results = [];
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          gist = _ref[_j];
          _results.push(gist.render());
        }
        return _results;
      }
    });
  };

  Gofer.Gist = Gist = (function() {
    function Gist(options) {
      this.render = __bind(this.render, this);
      this.load = __bind(this.load, this);
      this.id = options.id, this.parent = options.parent;
      this.load();
    }

    Gist.prototype.load = function() {
      var gist;
      gist = this;
      if (gist.request) {
        return gist.request;
      } else {
        return gist.request = $.ajax({
          url: "https://gist.github.com/" + gist.id + ".json",
          type: "GET",
          dataType: "jsonp",
          error: (function(_this) {
            return function(req, status, err) {
              return $.publish("gofer.gistLoadError", [err]);
            };
          })(this),
          success: (function(_this) {
            return function(data, status, req) {
              $.publish("gofer.gistLoadSuccess", [data]);
              gist.json = data;
              return gist.$div = $(data.div);
            };
          })(this)
        });
      }
    };

    Gist.prototype.render = function() {
      if (!this.request) {
        return this.load().then(this.render());
      }
      console.log("GIST");
      console.log(this);
      this.parent.$el.find("[data-gist-id='" + this.id + "']").replaceWith(this.$div);
      return $("head").append("<link rel='stylesheet' href='https://gist.github.com" + this.json.stylesheet + "'>");
    };

    return Gist;

  })();

  $.subscribe("gofer.pageAdd", function(event, fragment) {
    return fragment.getGists();
  });

}).call(this);
