// Generated by CoffeeScript 1.6.3
var Gist,
  _this = this,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Gofer.Fragment.prototype.getGists = function() {
  var fragment, gistIds, id, _i, _len;
  fragment = _this;
  fragment.gists = [];
  gistIds = [];
  fragment.$el.find("script[src^='https://gist.github.com']").each(function() {
    var id, urlPieces;
    urlPieces = this.src.split("/");
    id = urlPieces[urlPieces.length - 1].split(".")[0];
    $(this).attr("data-gist-id", id);
    return gistIds.push(id);
  });
  for (_i = 0, _len = gistIds.length; _i < _len; _i++) {
    id = gistIds[_i];
    fragment.gists.push(new Gofer.Gist({
      id: id,
      parent: fragment
    }));
  }
  return $.subscribe("gofer.pageRenderAll", function(event, page) {
    var gist, _j, _len1, _ref, _results;
    if (page.url === fragment.parent.url) {
      _ref = fragment.gists;
      _results = [];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        gist = _ref[_j];
        _results.push(gist.render());
      }
      return _results;
    }
  });
};

Gofer.Gist = Gist = (function() {
  function Gist(options) {
    this.render = __bind(this.render, this);
    this.load = __bind(this.load, this);
    this.id = options.id, this.parent = options.parent;
    this.load();
  }

  Gist.prototype.load = function() {
    if (this.request) {
      return this.request;
    } else {
      return this.request = $.ajax({
        url: "https://gist.github.com/" + this.id + ".json",
        type: "GET",
        dataType: "jsonp",
        error: function(req, status, err) {
          return $.publish("gofer.gistLoadError", [gist]);
        },
        success: function(data, status, req) {
          $.publish("gofer.gistLoadSuccess", [gist]);
          gist.loaded = true;
          return gist.json = data;
        }
      });
    }
  };

  Gist.prototype.render = function() {
    if (!this.request) {
      return this.load().then(this.render());
    }
    $("html").find("[data-gist-id='" + this.id + "']").replaceWith($(this.json.div));
    return $("head").append("<link rel='stylesheet' href='https://gist.github.com" + this.json.stylesheet + "'>");
  };

  return Gist;

})();
