// Generated by CoffeeScript 1.7.1
(function() {
  var cleanUpPlugins, jQueryPlugins, makePlugins;

  jQueryPlugins = [
    {
      name: "outerHTML",
      value: function() {
        var elem, tmp;
        elem = this[0];
        if (!elem) {
          return null;
        } else {
          if (typeof (tmp = elem.outerHTML) === "string") {
            return tmp;
          } else {
            return $('<div/>').html(this.eq(0).clone()).html();
          }
        }
      }
    }, {
      name: "findIn",
      value: function(selector) {
        return this.filter(selector).add(this.find(selector));
      }
    }
  ];

  makePlugins = function(plugins) {
    var plugin, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = plugins.length; _i < _len; _i++) {
      plugin = plugins[_i];
      _results.push($.fn[plugin.name] = plugin.value);
    }
    return _results;
  };

  cleanUpPlugins = function(plugins) {
    var plugin, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = plugins.length; _i < _len; _i++) {
      plugin = plugins[_i];
      _results.push($.fn[plugin.name] = void 0);
    }
    return _results;
  };

  makePlugins(jQueryPlugins);

}).call(this);
