// Generated by CoffeeScript 1.7.1

/*
Tiny Pub/Sub - v0.7.0 - 2013-01-29
https://github.com/cowboy/jquery-tiny-pubsub
Copyright (c) 2013 "Cowboy" Ben Alman; Licensed MIT
 */

(function() {
  (function($) {
    var hub;
    hub = $({});
    $.subscribe = function() {
      return hub.on.apply(hub, arguments);
    };
    $.unsubscribe = function() {
      return hub.off.apply(hub, arguments);
    };
    return $.publish = function() {
      return hub.trigger.apply(hub, arguments);
    };
  })(jQuery);

}).call(this);
